package com.kilivana.backend.logistics.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * The record that a delivery was handed over. Filed once per job, after the driver has
 * confirmed the customer's handover code, and carries the recipient's name, an optional
 * signature image and an optional photo of the goods at handover.
 *
 * <p>The signature is optional because the delivery OTP is the authoritative confirmation:
 * a driver who cannot capture a signature must still be able to file a proof.
 */
@Entity
@Table(name = "proof_of_deliveries")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProofOfDelivery {

    /** Primary key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The delivery job this proof belongs to. One proof per job. */
    @Column(nullable = false)
    private Long logisticsJobId;

    /** Name of the person who received the goods. */
    @Column(nullable = false)
    private String recipientName;

    /**
     * Optional. The delivery OTP is the authoritative confirmation of hand-over, so a driver
     * who cannot capture a signature must still be able to file a proof. These were all
     * NOT NULL, which rejected every proof that omitted a signature and made the OTP flow
     * impossible to complete.
     */
    private String signatureUrl;

    /** Optional photo of the goods at handover. */
    private String photoUrl;

    /** The delivery code the driver confirmed, for audit. Null when the job had no code. */
    private String otpReference;

    /** The instant the proof was filed on the server. Always populated. */
    @Column(nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime deliveredAt;
}