package com.kilivana.backend.logistics.entity;

import com.kilivana.backend.common.enums.DeliveryStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * One status change for a delivery job, optionally recorded with the position at the
 * moment it happened. This is the low-frequency status history; the high-frequency
 * position stream lives in {@code driver_locations}. A client reading tracking history
 * gets the status transitions with the position each was recorded at, which is enough
 * to redraw a journey without a separate position query.
 */
@Entity
@Table(name = "tracking_events")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrackingEvent {

    /** Primary key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The delivery job this event belongs to. */
    @Column(nullable = false)
    private Long logisticsJobId;

    /** The delivery status at the moment this event was recorded. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DeliveryStatus status;

    /** Latitude at the moment of the status change, when the caller supplied one. */
    private Double latitude;

    /** Longitude at the moment of the status change, when the caller supplied one. */
    private Double longitude;

    /** Free-text note, e.g. "left at gate" or "customer not home". */
    @Column(columnDefinition = "TEXT")
    private String note;

    /** The driver who recorded this event. */
    private Long driverId;

    /** The instant the event was recorded on the server. Always populated. */
    @Column(nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime recordedAt;
}